{% set name = "lsstdesc-dc2-dm-data" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/desc-dc2-dm-data/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 99f2589129afa30eb982d6aef4bd1d4c119c1de93a18bbda6a48c7c75ba19e3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - desc_dc2_dm_data
  requires:
    - stackvana =0.2021.6
    - deprecated <=1.2.10
  # no pip check since it fails
    - python {{ python_min }}

about:
  home: https://github.com/LSSTDESC/desc-dc2-dm-data
  summary: 'Providing consistent access to DC2 DM data products in DESC Python environments.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
